### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by mr-rsr** [minhhunghuynh1106/food-menus-data#3]
![image](https://user-images.githubusercontent.com/90951312/205970687-89f973ac-c90d-41b0-bc9a-f2581b0d18dd.png)
showing this error

**Comment by igdev116** [comment]
I'll fix that, this is the new heroku policy. Thank you.

**Comment by thallesraphael** [comment]
Hello. Same problem here.

**Comment by Damilarr** [comment]
I'm having the same issue,is it a problem with the hosting?

**Comment by igdev116** [comment]
This is because heroku doesn't let me use it for free anymore, i will use another service. Thanks you guys.

**Comment by igdev116** [comment]
Thanks for pull request @Damilarr

**Comment by Damilarr** [comment]
You're welcome!I think you can now close this issue
