### ISSUE TITLE
An error occurred in the application and your page could not be served

### ISSUE THREAD

**Issue by sebakthapa** [minhhunghuynh1106/food-menus-data#5]
![image](https://user-images.githubusercontent.com/71818293/212717985-48d135a8-2b55-475a-828e-155d19551dd6.png)

The log is like this:
![image](https://user-images.githubusercontent.com/71818293/212718182-3d531489-b9b8-4fe4-b8a2-fb8242bf052e.png)

Even the official example page "https://food-g-app.web.app/shop/best-foods" is not loading
Console error goes like this for this page:
![image](https://user-images.githubusercontent.com/71818293/212718407-a06828f3-6b05-437e-8c19-f0e860b9c357.png)

**Comment by sebakthapa** [comment]
I am unable to use this API any help?

**Comment by igdev116** [comment]
Please change your API url, new update on README
